### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by An9Yang**

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @alanfcb, can you check the permissions on your notion link? It didn't open for me. Thank you!

**Comment by An9Yang** [comment]
Hi Dan

Sorry for the late reply.

I changed the permission of link to everyone, should be working now. Please
try it again!
Sorry for this, but I was so confused because the former permission is for
“anyone with the link.”
I
 put link here just in case:
https://www.notion.so/Assignment-e3d9243581e948daaec5b7f646720b2e?pvs=4

Please let me know if there is anything else I need to do.

Best,
Annan

**Comment by shiffman** [comment]
Strange! I still am not able to get it to work! Don't worry, maybe we can look at the permissions together next class.

**Comment by An9Yang** [comment]
Hi Dan

I finally realized why my link was not working; I chose the share option
but not publish. I don't know when Notion changed to this; the share link
worked before, and there is also no Publish option.

Here is the share link:
https://lace-panama-99e.notion.site/Assignment-e3d9243581e948daaec5b7f646720b2e?pvs=4

I'm sorry for this bothering you. Please let me know if this one is still
not working.
Thank you! See you tomorrow.

Best Regards,
Annan

**Pull request merged**
